version: '3.8'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 5s
      retries: 10
      timeout: 5s

  app:
    build: .
    container_name: java_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/testdb
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  mysql_data:

