kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.33.1
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080   # frontend
        protocol: TCP
      - containerPort: 30808
        hostPort: 30808   # backend
        protocol: TCP
  - role: worker
    image: kindest/node:v1.33.1
  - role: worker
    image: kindest/node:v1.33.1
