# ===============================
# Namespace
# ===============================
apiVersion: v1
kind: Namespace
metadata:
  name: java-maven-app

---

# ===============================
# MySQL PVC, Deployment & Service
# ===============================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: java-maven-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: java-maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.33
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "testdb"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: java-maven-app
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP

---

# ===============================
# Backend Deployment & Service
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: java-maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: surendraprajapati/java-maven-3tier-mysql:latest
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service.java-maven-app:3306/testdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: java-maven-app
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30808
  type: NodePort

---

# ===============================
# Frontend Deployment & Service
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: java-maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-frontend
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      containers:
      - name: nginx-frontend
        image: surendraprajapati/3tier-frontend:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: java-maven-app
spec:
  selector:
    app: nginx-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
