apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: java-maven-app
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

