---
kind: Namespace
apiVersion: v1
metadata:
  name: java-maven-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: java-maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: surendraprajapati/java-maven-3tier-mysql:latest
        env:
        - name: DB_URL
          value: jdbc:mysql://mysql:3306/testdb
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: root
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: java-maven-app
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer



