
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  namespace: java-maven-app
spec:
  replicas: 2
  selector:       
    matchLabels:
      app: nginx-frontend
  template:
    metadata:
      labels:       
        app: nginx-frontend
    spec:
      containers:
       - name: nginx-frontend
         image: surendraprajapati/3tier-frontend
         ports:
         - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: java-maven-app
spec:
  selector:
    app: nginx-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort

         
      
    
    
