name: CI with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build & Run Docker Compose
        run: |
          docker-compose up --build -d

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            docker exec mysql_db mysqladmin ping -uroot -prootpassword &> /dev/null && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run Java Controller in App container
        run: |
          docker exec java_app java -cp app.jar com.example.controller.UserController

      # - name: Tear down
      #   run: docker-compose down


