name: Sync to Azure DevOps

on:
  push:
    branches:
      - main   # or whatever branch you want synced

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Azure DevOps
        run: |
          git remote add azure https://$(echo "${{ secrets.AZURE_USERNAME }}"):${{ secrets.AZURE_PAT }}@dev.azure.com/ashukumavat2410/_git/Java-YAML-CICD
          git push --force azure main
