name: Mirror to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Azure DevOps
        env:
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
        run: |
          git remote add azure https://$AZURE_USERNAME:$AZURE_PAT@dev.azure.com/ashukumavat2410/_git/Java-YAML-CICD
          git push --force azure main
