name: Mirror to Azure DevOps

on:
  push:
    branches:
      - main   # or master, depending on your repo

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mirror to Azure DevOps
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git remote add azure https://$(AZURE_USERNAME):$(AZURE_PAT)@dev.azure.com/<ORG>/<PROJECT>/_git/<REPO>
          git push azure main --force
        env:
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
