name: Mirror to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config --global user.email "${{ secrets.AZUSER_EMAIL }}"
          git config --global user.name "${{ secrets.AZUSERNAME }}"

      - name: Mirror to Azure DevOps
        env:
          AZUSERNAME: ${{ secrets.AZUSERNAME }}
          AZUREPAT: ${{ secrets.AZUREPAT }}
          AZORG: ${{ secrets.AZORG }}
          AZREPO: ${{ secrets.AZREPO }}  # Repo name in Azure DevOps
        run: |
          echo "Cloning Azure DevOps repo..."
          git clone https://$AZUSERNAME:$AZUREPAT@dev.azure.com/$AZORG/$AZREPO/_git/$AZREPO azure_repo
          
          echo "Copying files from GitHub repo to Azure DevOps repo..."
          cp -r ./* azure_repo/
          
          cd azure_repo
          git add .
          git commit -m "Sync from GitHub to Azure DevOps" || echo "No changes to commit"
          git push origin main --force
