name: Sync GitHub to Azure DevOps
on:
  push:
    branches:
      - main # or the name of your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetches all history for all branches and tags

    - name: Configure Git
      run: |
        git config --global user.email "ashukumavat2410@gmail.com"
        git config --global user.name "ashukumavat2410@gmail.com"

    - name: Push to Azure DevOps
      env:
        ADO_PAT: ${{ secrets.AZURE_PAT }}
      run: |
        git remote add azuredevops https://ashukumavat2410@dev.azure.com/ashukumavat2410/Java-YAML-CICD/_git/Java-YAML-CICD
        git push --force azuredevops main
